APP_TITLE="Stream Deck UI"
APP_MENU_FILENAME="Stream Deck UI"
APP_MENU_COMMENT="Get ready to revolutionize your workflow"
PYTHON_PACKAGE_NAME="streamdeck_ui"
VENV_SUFFIX=""
UDEV_RULES_URL="https://raw.githubusercontent.com/streamdeck-linux-gui/streamdeck-linux-gui/main/udev/60-streamdeck.rules"
UDEV_TARGET_PATH="/etc/udev/rules.d/60-streamdeck.rules"
